import { buildGenerationContext as buildCtx } from './operationContext.js';
import { exampleFromSchema } from './schemaUtils.js';
import { generateCurlSnippet, generateFetchSnippet } from './snippets.js';
import { generateTypeScriptClient, generateJavaScriptClient, generatePythonClient, generateExpressStub } from './generators.js';

export { exampleFromSchema, schemaToTsType, schemaToNamedTsInterfaces } from './schemaUtils.js';
export { generateCurlSnippet, generateFetchSnippet } from './snippets.js';
export { generateTypeScriptClient, generateJavaScriptClient, generatePythonClient, generateExpressStub } from './generators.js';

/**
 * Full context for codegen including derived example request body.
 * @param {object} contract App contract row
 */
export function buildGenerationContext(contract) {
  const ctx = buildCtx(contract);
  const exampleBody = ctx.requestSchema ? exampleFromSchema(ctx.requestSchema) : null;
  return { ...ctx, exampleBody };
}

export const ARTIFACT_TABS = [
  { id: 'curl', label: 'cURL' },
  { id: 'fetch', label: 'Fetch' },
  { id: 'typescript', label: 'TypeScript' },
  { id: 'python', label: 'Python' },
  { id: 'express', label: 'Express' },
  { id: 'markdown', label: 'Docs (MD)' },
];

/**
 * @param {'curl'|'fetch'|'typescript'|'python'|'express'|'markdown'} id
 * @param {ReturnType<buildGenerationContext>} ctx
 */
export function generateArtifactText(id, ctx) {
  switch (id) {
    case 'curl':
      return generateCurlSnippet(ctx);
    case 'fetch':
      return generateFetchSnippet(ctx);
    case 'typescript':
      return generateTypeScriptClient(ctx);
    case 'python':
      return generatePythonClient(ctx);
    case 'express':
      return generateExpressStub(ctx);
    case 'markdown':
      return generateMarkdownDocs(ctx);
    default:
      return '';
  }
}

export function artifactDownloadName(id, operationId) {
  const slug = String(operationId || 'api').replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-|-$/g, '') || 'api';
  const map = {
    curl: `${slug}-example.curl.txt`,
    fetch: `${slug}-fetch-example.js`,
    typescript: `${slug}-client.ts`,
    python: `${slug}-client.py`,
    express: `${slug}-express-route.js`,
    markdown: `${slug}-api.md`,
  };
  return map[id] || `${slug}-snippet.txt`;
}

function generateMarkdownDocs(ctx) {
  const lines = [];
  lines.push(`# ${ctx.summary}`);
  lines.push('');
  lines.push(`- **Method:** \`${String(ctx.method || '').toUpperCase()}\``);
  lines.push(`- **Path:** \`${ctx.pathTemplate}\``);
  lines.push(`- **operationId:** \`${ctx.operationId}\``);
  lines.push(`- **Base URL:** \`${ctx.baseUrl}\``);
  lines.push(`- **Full URL:** \`${ctx.fullUrl}\``);
  lines.push('');

  if (ctx.securityHints?.length) {
    lines.push('## Auth (from OpenAPI security schemes)');
    for (const h of ctx.securityHints) {
      lines.push(`- Header \`${h.header}\`: \`${h.value}\`${h.scheme ? ` (_${h.scheme}_)` : ''}`);
    }
    lines.push('');
  }

  if (ctx.requestSchema?.properties && Object.keys(ctx.requestSchema.properties).length) {
    lines.push('## Request body (JSON)');
    lines.push('');
    lines.push('| Field | Type | Required |');
    lines.push('| --- | --- | --- |');
    const req = new Set(ctx.requestSchema.required || []);
    for (const [k, v] of Object.entries(ctx.requestSchema.properties)) {
      const t = Array.isArray(v?.type) ? v.type.join(' | ') : v?.type || 'unknown';
      lines.push(`| \`${k}\` | ${t} | ${req.has(k) ? 'yes' : 'no'} |`);
    }
    lines.push('');
    lines.push('### Example payload');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(ctx.exampleBody ?? {}, null, 2));
    lines.push('```');
    lines.push('');
  }

  if (ctx.responseSchema) {
    lines.push(`## Response (${ctx.responseStatusCode})`);
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(exampleFromSchema(ctx.responseSchema), null, 2));
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by PulseAPI from the stored OpenAPI document._');
  return lines.join('\n');
}
